0-preprocessor

diff --git a/alx-low_level_programming/0x00-hello_world/0-preprocessor b/alx-low_level_programming/0x00-hello_world/0-preprocessor
--- a/alx-low_level_programming/0x00-hello_world/0-preprocessor
+++ b/alx-low_level_programming/0x00-hello_world/0-preprocessor
@@ -1,2 +1,7 @@
 #!/bin/bash
+if [ -z "$CFILE" ]; then
+    echo "Error: CFILE variable is not set."
+    exit 1
+fi
+
 gcc -E "$CFILE" -o c
